FROM ndn-base:v1

RUN  apt-get install -y iproute2 iputils-ping pkg-config nano  sudo psmisc 

WORKDIR /src

COPY protocol/producer/build/producer_average ./
COPY protocol/producer/average.so ./

CMD ["./producer_average"]
